### ISSUE TITLE
Photo can't change

### ISSUE THREAD

**Issue by Riansaga** [Jieyab89/Finde-Me-simple-web-application#1]
Photo can't change and missing page vip user in home.blade.php fix it

**Comment by Jieyab89** [comment]
Hi Rian

Thanks for trying. Have you followed my tutorial before? You can read on the readme

Did you get an error? If yes, show the error and its code. For the VIP user case I will make it later

I have tried and succeeded in uploading photos make sure you fill out the input form to update and please can be seen in the user folder make sure your files are saved

Thanks

Picture 
![satu](https://user-images.githubusercontent.com/71226310/136699744-42b8feab-e9c1-46d5-aa2e-84b38a9814e2.PNG)
![tiga](https://user-images.githubusercontent.com/71226310/136699747-84b24c05-08b8-4f7e-9811-f8d599cae8f1.PNG)
![dua](https://user-images.githubusercontent.com/71226310/136699748-e5986c73-004f-4d95-a7e5-c6313cffa23e.PNG)


[](url)
