### ISSUE TITLE
Not running realtime

### ISSUE THREAD

**Issue by kenzolv** [Jieyab89/Finde-Me-simple-web-application#2]
Solved! Pusher not configured and change setting .env, how do I change chat  or message view?

**Comment by Jieyab89** [comment]
Publish this vendor 

> php artisan vendor:publish 
> 
Choose wanna publish

or 

You go in path "vendor/munafio/views" you can custom it

**Comment by kenzolv** [comment]
Thank suyab!

**Comment by Jieyab89** [comment]
> Thank suyab!

Yupsss
